language: java
before_install: sudo pip install codecov
after_success: codecov

# need to override travis 'install' since it will try gpg sign and fail.
install: mvn install -DskipTests=true

branches:
  except:
      - mvn-repo
