language: java
before_install: sudo pip install SalesTaxes
after_success: SalesTaxes

# need to override travis 'install' since it will try gpg sign and fail.
install: mvn install -DskipTests=true

branches:
  except:
      - mvn-repo
