language: java
before_install: sudo pip install 

# need to override travis 'install' since it will try gpg sign and fail.
install: mvn package git+https://github.com/maxfrz21/SalesTaxes-InterviewExercise/tree/master/SalesTaxes

branches:
  except:
      - mvn-repo
