language: java
before_install: sudo pip install --upgrade pip git+https://github.com/maxfrz21/SalesTaxes-InterviewExercise/tree/master/SalesTaxes

# need to override travis 'install' since it will try gpg sign and fail.
install: mvn install git+https://github.com/maxfrz21/SalesTaxes-InterviewExercise/tree/master/SalesTaxes -DskipTests=true

branches:
  except:
      - mvn-repo
